config/routes.rb
CollegeChecklist::Application.routes.draw do
  resources :checks

  resources :checklists

  resources :college_lists

end

app/models/college_list.rb
class CollegeList < ActiveRecord::Base
  attr_accessible :accepted, :completed_steps, :date_accepted, :date_complete, :date_due, :incomplete_steps, :name, :priority, :user_id
end

app/controllers/college_lists_controller.rb
class CollegeListsController < ApplicationController
  # GET /college_lists
  # GET /college_lists.json
  def index
    @college_lists = CollegeList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @college_lists }
    end
  end

  # GET /college_lists/1
  # GET /college_lists/1.json
  def show
    @college_list = CollegeList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @college_list }
    end
  end

  # GET /college_lists/new
  # GET /college_lists/new.json
  def new
    @college_list = CollegeList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @college_list }
    end
  end

  # GET /college_lists/1/edit
  def edit
    @college_list = CollegeList.find(params[:id])
  end

  # POST /college_lists
  # POST /college_lists.json
  def create
    @college_list = CollegeList.new(params[:college_list])

    respond_to do |format|
      if @college_list.save
        format.html { redirect_to @college_list, notice: 'College list was successfully created.' }
        format.json { render json: @college_list, status: :created, location: @college_list }
      else
        format.html { render action: "new" }
        format.json { render json: @college_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /college_lists/1
  # PUT /college_lists/1.json
  def update
    @college_list = CollegeList.find(params[:id])

    respond_to do |format|
      if @college_list.update_attributes(params[:college_list])
        format.html { redirect_to @college_list, notice: 'College list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @college_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /college_lists/1
  # DELETE /college_lists/1.json
  def destroy
    @college_list = CollegeList.find(params[:id])
    @college_list.destroy

    respond_to do |format|
      format.html { redirect_to college_lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/college_lists_helper.rb
module CollegeListsHelper
end

app/views/college_lists/_form.html.erb
<%= form_for(@college_list) do |f| %>
  <% if @college_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college_list.errors.count, "error") %> prohibited this college_list from being saved:</h2>

      <ul>
      <% @college_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :date_due %><br />
    <%= f.datetime_select :date_due %>
  </div>
  <div class="field">
    <%= f.label :date_complete %><br />
    <%= f.datetime_select :date_complete %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.check_box :accepted %>
  </div>
  <div class="field">
    <%= f.label :date_accepted %><br />
    <%= f.datetime_select :date_accepted %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :completed_steps %><br />
    <%= f.number_field :completed_steps %>
  </div>
  <div class="field">
    <%= f.label :incomplete_steps %><br />
    <%= f.number_field :incomplete_steps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/college_lists/edit.html.erb
<h1>Editing college_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @college_list %> |
<%= link_to 'Back', college_lists_path %>

app/views/college_lists/index.html.erb
<h1>Listing college_lists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Priority</th>
    <th>Date due</th>
    <th>Date complete</th>
    <th>Accepted</th>
    <th>Date accepted</th>
    <th>User</th>
    <th>Completed steps</th>
    <th>Incomplete steps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @college_lists.each do |college_list| %>
  <tr>
    <td><%= college_list.name %></td>
    <td><%= college_list.priority %></td>
    <td><%= college_list.date_due %></td>
    <td><%= college_list.date_complete %></td>
    <td><%= college_list.accepted %></td>
    <td><%= college_list.date_accepted %></td>
    <td><%= college_list.user_id %></td>
    <td><%= college_list.completed_steps %></td>
    <td><%= college_list.incomplete_steps %></td>
    <td><%= link_to 'Show', college_list %></td>
    <td><%= link_to 'Edit', edit_college_list_path(college_list) %></td>
    <td><%= link_to 'Destroy', college_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New College list', new_college_list_path %>

app/views/college_lists/new.html.erb
<h1>New college_list</h1>

<%= render 'form' %>

<%= link_to 'Back', college_lists_path %>

app/views/college_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @college_list.name %>
</p>

<p>
  <b>Priority:</b>
  <%= @college_list.priority %>
</p>

<p>
  <b>Date due:</b>
  <%= @college_list.date_due %>
</p>

<p>
  <b>Date complete:</b>
  <%= @college_list.date_complete %>
</p>

<p>
  <b>Accepted:</b>
  <%= @college_list.accepted %>
</p>

<p>
  <b>Date accepted:</b>
  <%= @college_list.date_accepted %>
</p>

<p>
  <b>User:</b>
  <%= @college_list.user_id %>
</p>

<p>
  <b>Completed steps:</b>
  <%= @college_list.completed_steps %>
</p>

<p>
  <b>Incomplete steps:</b>
  <%= @college_list.incomplete_steps %>
</p>


<%= link_to 'Edit', edit_college_list_path(@college_list) %> |
<%= link_to 'Back', college_lists_path %>