config/routes.rb
CollegeChecklist::Application.routes.draw do
  resources :checks

  resources :checklists

  resources :college_lists

end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  belongs_to :college_list
  attr_accessible :completed, :date_complete, :due_date, :name
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  # GET /checklists
  # GET /checklists.json
  def index
    @checklists = Checklist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checklists }
    end
  end

  # GET /checklists/1
  # GET /checklists/1.json
  def show
    @checklist = Checklist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/new
  # GET /checklists/new.json
  def new
    @checklist = Checklist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/1/edit
  def edit
    @checklist = Checklist.find(params[:id])
  end

  # POST /checklists
  # POST /checklists.json
  def create
    @checklist = Checklist.new(params[:checklist])

    respond_to do |format|
      if @checklist.save
        format.html { redirect_to @checklist, notice: 'Checklist was successfully created.' }
        format.json { render json: @checklist, status: :created, location: @checklist }
      else
        format.html { render action: "new" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checklists/1
  # PUT /checklists/1.json
  def update
    @checklist = Checklist.find(params[:id])

    respond_to do |format|
      if @checklist.update_attributes(params[:checklist])
        format.html { redirect_to @checklist, notice: 'Checklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/1
  # DELETE /checklists/1.json
  def destroy
    @checklist = Checklist.find(params[:id])
    @checklist.destroy

    respond_to do |format|
      format.html { redirect_to checklists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_form.html.erb
<%= form_for(@checklist) do |f| %>
  <% if @checklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checklist.errors.count, "error") %> prohibited this checklist from being saved:</h2>

      <ul>
      <% @checklist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :college_list %><br />
    <%= f.text_field :college_list %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :date_complete %><br />
    <%= f.datetime_select :date_complete %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checklists/edit.html.erb
<h1>Editing checklist</h1>

<%= render 'form' %>

<%= link_to 'Show', @checklist %> |
<%= link_to 'Back', checklists_path %>

app/views/checklists/index.html.erb
<h1>Listing checklists</h1>

<table>
  <tr>
    <th>College list</th>
    <th>Name</th>
    <th>Due date</th>
    <th>Date complete</th>
    <th>Completed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checklists.each do |checklist| %>
  <tr>
    <td><%= checklist.college_list %></td>
    <td><%= checklist.name %></td>
    <td><%= checklist.due_date %></td>
    <td><%= checklist.date_complete %></td>
    <td><%= checklist.completed %></td>
    <td><%= link_to 'Show', checklist %></td>
    <td><%= link_to 'Edit', edit_checklist_path(checklist) %></td>
    <td><%= link_to 'Destroy', checklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checklist', new_checklist_path %>

app/views/checklists/new.html.erb
<h1>New checklist</h1>

<%= render 'form' %>

<%= link_to 'Back', checklists_path %>

app/views/checklists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>College list:</b>
  <%= @checklist.college_list %>
</p>

<p>
  <b>Name:</b>
  <%= @checklist.name %>
</p>

<p>
  <b>Due date:</b>
  <%= @checklist.due_date %>
</p>

<p>
  <b>Date complete:</b>
  <%= @checklist.date_complete %>
</p>

<p>
  <b>Completed:</b>
  <%= @checklist.completed %>
</p>


<%= link_to 'Edit', edit_checklist_path(@checklist) %> |
<%= link_to 'Back', checklists_path %>