config/routes.rb
CollegeChecklist::Application.routes.draw do
  resources :checks

  resources :checklists

  resources :college_lists

end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :college_list
  attr_accessible :completed, :date_complete, :due_date, :name
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  # GET /checks
  # GET /checks.json
  def index
    @checks = Check.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checks }
    end
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
    @check = Check.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @check }
    end
  end

  # GET /checks/new
  # GET /checks/new.json
  def new
    @check = Check.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @check }
    end
  end

  # GET /checks/1/edit
  def edit
    @check = Check.find(params[:id])
  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(params[:check])

    respond_to do |format|
      if @check.save
        format.html { redirect_to @check, notice: 'Check was successfully created.' }
        format.json { render json: @check, status: :created, location: @check }
      else
        format.html { render action: "new" }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checks/1
  # PUT /checks/1.json
  def update
    @check = Check.find(params[:id])

    respond_to do |format|
      if @check.update_attributes(params[:check])
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check = Check.find(params[:id])
    @check.destroy

    respond_to do |format|
      format.html { redirect_to checks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= form_for(@check) do |f| %>
  <% if @check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check.errors.count, "error") %> prohibited this check from being saved:</h2>

      <ul>
      <% @check.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :date_complete %><br />
    <%= f.datetime_select :date_complete %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :college_list %><br />
    <%= f.text_field :college_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing check</h1>

<%= render 'form' %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<h1>Listing checks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Due date</th>
    <th>Date complete</th>
    <th>Completed</th>
    <th>College list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checks.each do |check| %>
  <tr>
    <td><%= check.name %></td>
    <td><%= check.due_date %></td>
    <td><%= check.date_complete %></td>
    <td><%= check.completed %></td>
    <td><%= check.college_list %></td>
    <td><%= link_to 'Show', check %></td>
    <td><%= link_to 'Edit', edit_check_path(check) %></td>
    <td><%= link_to 'Destroy', check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Check', new_check_path %>

app/views/checks/new.html.erb
<h1>New check</h1>

<%= render 'form' %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @check.name %>
</p>

<p>
  <b>Due date:</b>
  <%= @check.due_date %>
</p>

<p>
  <b>Date complete:</b>
  <%= @check.date_complete %>
</p>

<p>
  <b>Completed:</b>
  <%= @check.completed %>
</p>

<p>
  <b>College list:</b>
  <%= @check.college_list %>
</p>


<%= link_to 'Edit', edit_check_path(@check) %> |
<%= link_to 'Back', checks_path %>